<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 */
function rsvp_list_form_node_form_alter(&$form, FormStateInterface $form_state) {
  $node = $form_state->getFormObject()->getEntity();
  $current_node_type = $node->getType();
  $config = \Drupal::config('rsvp_list.settings');
  //$config = $this->config('rsvp_list.settings');
  $types = $config->get('allowed_types');

  if(in_array($current_node_type, $types)) {
    $form['rsvp_list'] = [
      '#type' => 'details',
      '#title' => t('Enable Rsvp Collection'),
      '#access' => \Drupal::currentUser()->hasPermission('administer rsvp_list'),
      '#group' => 'advanced',
      '#weight' => 100,
    ];

    $enabler = \Drupal::service('rsvp_list.enabler');
    $form['rsvp_list']['rsvp_list_enabled'] = [
      '#type' => 'checkbox',
      '#title' => t('Collect RSVP email addresses for this node'),
      '#default_value' => $enabler->isEnabled($node),
    ];

    foreach(array_keys($form['actions']) as $action) {
      if($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
        $form['actions'][$action]['#submit'][] = 'rsvp_list_form_node_form_submit';
      }
    }
  }
}

function rsvp_list_form_node_form_submit(array $form, FormStateInterface $form_state) {
  $enabler = \Drupal::service('rsvp_list.enabler');
  $node = $form_state->getFormObject()->getEntity();
  if ($enabled = $form_state->getValue('rsvp_list_enabled')) {
    $enabler->setEnabled($node);
  }
  else {
    $enabler->delEnabled($node);
  }
}
