<?php
/**
 * Implements hook_schema().
 *
 */
function rsvp_list_schema() {
  $schema['rsvplist_enabled'] = [
    'description' => 'Tracks whether rsvplist is enabled for a node.',
    'fields' => [
      'nid' => [
        'description' => 'The {node}.nid that has rsvplist enabled.',
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ],
    ],
    'primary key' => array('nid'),
  ];
  return $schema;
}
